printWidth: 100
tabWidth: 2
useTabs: true
semi: true
singleQuote: false
quoteProps: "consistent"
trailingComma: "es5"
bracketSpacing: true
bracketSameLine: false
arrowParens: "always"
requirePragma: false
insertPragma: false
htmlWhitespaceSensitivity: "ignore"
endOfLine: "lf"
embeddedLanguageFormatting: "auto"
singleAttributePerLine: true
